create type star_rating as enum ('1', '2', '3', '4', '5');

create table bookmarks (
  id integer primary key generated by default as identity,
  title text not null,
  url text not null,
  rating star_rating not null,
  description text
);